# -*- coding: utf-8 -*-
"""Supervised.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cWMQfLMeTsOepwnc7gwWbTU48rJNn92g

<font color="#FAC2E7" size="7"><b>CASE 2 Grey Hair Converage

(แบรนด์แชมพูปิดผมขาว DeeAsh)</b></font>

##**รายชื่อสมาชิก**

**1. ทิพวรรณ  ยิ้มเนียม  1660903921**

**2. สิริกานต์  ปุริสังคหะ  1660904101**

**3. อรพินธ์   นาคุณ    1660904689**

<font color="#C9ABB2" size="6"><b>Data Dictionary</b></font>

`gender` = เพศของคุณ

`age` = อายุของคุณ

`region` = คุณอยู่ในภาคไหนของประเทศไทย?

`used_products` = คุณเคยใช้ผลิตภัณฑ์ประเภทไหนในการปิดผมหงอกด้วยตัวเองบ้าง?  (เลือกได้มากกว่า 1 ข้อ)

`used_shampoo` = คุณเคยใช้ “แชมพูปิดผมขาว” หรือไม่? (เช่น HerbaSure, DeeAsh, Lyora แบบสระ ฯลฯ)

`usage_trigger` = ครั้งล่าสุดที่คุณใช้แชมพูปิดผมขาว เกิดจากอะไร? (พิมพ์ตอบสั้นๆอิสระได้เลย เช่น เห็นผมขาว, มีคนทัก, ต้องไปงาน ฯลฯ)

`feeling_after_use` = คุณรู้สึกยังไงหลังใช้เสร็จ แล้วเห็นผมหงอกหายไป? (อยากได้ความรู้สึกจริงๆ เช่น รู้สึกเหมือนตัวเองกลับมาอีกครั้ง, หน้าเด็ก, มั่นใจขึ้น ฯลฯ)

`desired_compliment` = ถ้ามีใครชมคุณหลังใช้เสร็จ คุณอยากได้ยินคำพูดแบบไหนมากที่สุด?

`expected_features` = ถ้าให้เลือก “สิ่งที่แชมพูปิดผมขาวควรมี” คุณคาดหวังอะไรที่สุด? (เลือกได้มากกว่า 1 ข้อ)

`usage_occasion` = โดยปกติคุณมักใช้แชมพูปิดผมขาวในช่วงไหนบ้าง?(เลือกได้หลายข้อ หากมีช่วงอื่นๆพิมพ์ตอบเพิ่มได้เลยค่ะ)

`occasion_reason` = จากข้อด้านบน เพราะอะไรถึงต้องใช้ในโมเมนต์เหล่านี้?

`current_brand` = ตอนนี้คุณใช้แชมพูปิดผมขาวของแบรนด์ไหนอยู่บ่อยที่สุด?(เลือก 1 ข้อ หรือพิมพ์เพิ่มได้)

`brand_reason` = ทำไมคุณถึงเลือกแบรนด์นั้น? (ขอเหตุผลจริงๆ เช่น ใช้ง่าย, กลิ่นไม่ฉุน, เห็นจากเชลฟ์, ราคาดี, พรีเซนเตอร์, เคยเห็นโฆษณา ฯลฯ)

`pain_points` = มีอะไรที่คุณ “ยังไม่พอใจ” หรือ “อยากให้ดีกว่านี้” จากแบรนด์ที่ใช้อยู่ตอนนี้ไหม?

`purchase_channels` = คุณซื้อผลิตภัณฑ์แชมพูปิดผมขาวจากช่องทางไหนบ้าง?

`pain_points_std` =

`brand_reason_std` =

---

**1. gender (เพศ)**
*   0: 'LGBTQ'
*   1: 'ชาย'
*   2: 'หญิง'


**2. age (อายุ)**
*   0: '30–34 ปี'
*   1: '35–44 ปี'
*   2: '45–54 ปี'
*   3: '55 ปีขึ้นไป'


**3. region (ภูมิภาค)**
*   0: 'กทม. & ปริมณฑล'
*   1: 'ภาคตะวันตก'
*   2: 'ภาคตะวันออก'
*   3: 'ภาคอีสาน'
*   4: 'ภาคเหนือ'
*   5: 'ภาคใต้'



---
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib as mpl
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, classification_report,
    roc_auc_score, roc_curve
)
from sklearn.utils.class_weight import compute_class_weight

import urllib.request, os

font_path = 'thsarabunnew-webfont.ttf'
if not os.path.exists(font_path):
    try:
        url = 'https://github.com/Phonbopit/sarabun-webfont/raw/master/fonts/thsarabunnew-webfont.ttf'
        urllib.request.urlretrieve(url, font_path)
        print("★ ดาวน์โหลดฟอนต์สำเร็จ")
    except Exception as e:
        print(f"⚠️  ดาวน์โหลดฟอนต์ไม่สำเร็จ ({e}) — ใช้ฟอนต์ default แทน")
        font_path = None

if font_path and os.path.exists(font_path):
    fm.fontManager.addfont(font_path)
    mpl.rc('font', family='TH Sarabun New', size=14)
else:
    mpl.rc('font', size=12)

# ★ โหลดข้อมูลจาก ML-Ready CSV (เดียวกับ Unsupervised)
df = pd.read_csv('DeeAsh_ML_Final_Ready.csv', encoding='utf-8-sig')

print("★ โหลดข้อมูลสำเร็จ")
print(f"   จำนวนแถว : {len(df)} แถว")
print(f"   คอลัมน์  : {list(df.columns)}")

"""##**Feature Engineering & Encoding**"""

# print("★ Feature Engineering & Encoding\n")

# df_sl = df.copy()

# # Ordinal Encoding — age
# age_mapping = {
#     'ต่ำกว่า 30 ปี': 1,
#     '30–34 ปี'     : 2,
#     '35–44 ปี'     : 3,
#     '45–54 ปี'     : 4,
#     '55 ปีขึ้นไป'  : 5,
# }
# df_sl['age_encoded'] = df_sl['age'].map(age_mapping)

# # One-Hot Encoding — region, pain_points_std, brand_reason_std
# # cols_to_encode = ['region', 'pain_points_std', 'brand_reason_std']
# # df_enc = pd.get_dummies(df_sl, columns=cols_to_encode, drop_first=True)

# # กำหนด Features (X) และ Target (y)
# drop_cols = [
#     'age', 'gender',                          # ★ ตัด gender ออก
#     'used_products', 'used_shampoo', 'usage_trigger',
#     'feeling_after_use', 'desired_compliment', 'expected_features',
#     'usage_occasion', 'occasion_reason', 'current_brand',
#     'brand_reason', 'pain_points', 'purchase_channels',
#     'main_channel', 'Target_Winning_Zone',
# ]
# X = df_enc.drop(columns=drop_cols, errors='ignore')
# y = df_enc['Target_Winning_Zone']

# # MinMaxScaler
# scaler   = MinMaxScaler()
# X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

# print(f"   Features ที่ใช้ ({X_scaled.shape[1]} ตัว): {list(X_scaled.columns)}")
# print(f"   Target distribution:\n{y.value_counts().rename({1:'Winning Zone (1)', 0:'Non-Target (0)'}).to_string()}")

print("★ Feature Engineering & Encoding\n")

df_sl = df.copy()

# One-Hot Encoding เฉพาะ main_channel (เป็น categorical ที่ยังไม่ถูก encode)
df_enc = pd.get_dummies(df_sl, columns=['main_channel'], drop_first=True)

# กำหนด Features (X) — ใช้เฉพาะ encoded columns + main_channel dummies
# ตัด text columns ทิ้งทั้งหมด, ตัด Target ออก, ตัด columns ซ้ำออก
drop_cols = [
    # Text columns ดิบ (ไม่ใช้ใน model)
    'gender', 'age', 'region',
    'used_products', 'used_shampoo', 'usage_trigger',
    'feeling_after_use', 'desired_compliment', 'expected_features',
    'usage_occasion', 'occasion_reason', 'current_brand',
    'brand_reason', 'pain_points', 'purchase_channels',
    'pain_points_std', 'brand_reason_std',
    # Target
    'Target_Winning_Zone',
]

X = df_enc.drop(columns=drop_cols, errors='ignore')
y = df_enc['Target_Winning_Zone']

# ตรวจสอบ features ที่ใช้
print(f"   Features ที่ใช้ ({X.shape[1]} ตัว): {list(X.columns)}")
print(f"\n   Target distribution:")
print(f"   Winning Zone (1) : {(y==1).sum()} คน ({(y==1).mean()*100:.1f}%)")
print(f"   Non-Target  (0)  : {(y==0).sum()} คน ({(y==0).mean()*100:.1f}%)")

# MinMaxScaler
scaler   = MinMaxScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

"""##**แบ่งข้อมูล Train/Test**"""

# print("★ Data Splitting\n")

# X_train, X_test, y_train, y_test = train_test_split(
#     X_scaled, y, test_size=0.2, random_state=42, stratify=y
# )

# print(f"   Training Set : {len(X_train)} แถว")
# print(f"   Testing Set  : {len(X_test)} แถว")
# print(f"   สัดส่วน Winning Zone ใน Train: {y_train.mean()*100:.1f}%")
# print(f"   สัดส่วน Winning Zone ใน Test : {y_test.mean()*100:.1f}%")

print("★ Data Splitting\n")

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y,
    test_size=0.2,
    random_state=42,
    stratify=y          # รักษาสัดส่วน class ใน train/test
)

print(f"   Training Set : {len(X_train)} แถว")
print(f"   Testing Set  : {len(X_test)} แถว")
print(f"   สัดส่วน Winning Zone ใน Train : {y_train.mean()*100:.1f}%")
print(f"   สัดส่วน Winning Zone ใน Test  : {y_test.mean()*100:.1f}%")

"""##**Model Training**"""

# # Model Training (5 โมเดล)

# print("★ Model Training (5 Models)\n")

# # คำนวณ class_weight เพื่อจัดการ Class Imbalance
# classes      = np.unique(y_train)
# class_w      = compute_class_weight('balanced', classes=classes, y=y_train)
# weight_dict  = dict(zip(classes, class_w))

# models = {
#     'Logistic Regression'   : LogisticRegression(max_iter=1000, random_state=42,
#                                                   class_weight=weight_dict),
#     'Decision Tree'         : DecisionTreeClassifier(max_depth=4, random_state=42,
#                                                      class_weight=weight_dict),
#     'Random Forest'         : RandomForestClassifier(n_estimators=100, random_state=42,
#                                                      class_weight=weight_dict),
#     'Gradient Boosting'     : GradientBoostingClassifier(n_estimators=100, random_state=42),
#     'K-Nearest Neighbors'   : KNeighborsClassifier(n_neighbors=5),
# }

# results = []
# trained_models = {}

# for name, model in models.items():
#     model.fit(X_train, y_train)
#     y_pred = model.predict(X_test)

#     # Cross-Validation (5-fold) บนชุด Train
#     cv_scores = cross_val_score(model, X_scaled, y, cv=5, scoring='f1')

#     results.append({
#         'Model'       : name,
#         'Accuracy'    : accuracy_score(y_test, y_pred),
#         'Precision'   : precision_score(y_test, y_pred, zero_division=0),
#         'Recall'      : recall_score(y_test, y_pred, zero_division=0),
#         'F1-Score'    : f1_score(y_test, y_pred, zero_division=0),
#         'CV F1 Mean'  : cv_scores.mean(),
#         'CV F1 Std'   : cv_scores.std(),
#     })
#     trained_models[name] = (model, y_pred)
#     print(f"   ✓ {name} — F1: {f1_score(y_test, y_pred, zero_division=0):.3f}")

# results_df = pd.DataFrame(results).sort_values('F1-Score', ascending=False).reset_index(drop=True)

# print("\n★ Model Comparison Table:")
# print(results_df.round(3).to_string(index=False))

print("\n★ Model Training (5 Models)\n")

# ✅ คำนวณ class_weight จาก Train set เท่านั้น (ไม่ใช้ทั้ง dataset)
classes     = np.unique(y_train)
class_w     = compute_class_weight('balanced', classes=classes, y=y_train)
weight_dict = dict(zip(classes, class_w))
print(f"   class_weight : {weight_dict}")

# ✅ Gradient Boosting ไม่รองรับ class_weight parameter โดยตรง
#    → แก้ด้วย sample_weight ตอน fit แทน
sample_weights_train = np.where(
    y_train == 1,
    weight_dict[1],
    weight_dict[0]
)

models = {
    'Logistic Regression' : LogisticRegression(
        max_iter=1000, random_state=42, class_weight=weight_dict
    ),
    'Decision Tree'       : DecisionTreeClassifier(
        max_depth=4, random_state=42, class_weight=weight_dict
    ),
    'Random Forest'       : RandomForestClassifier(
        n_estimators=100, random_state=42, class_weight=weight_dict
    ),
    'Gradient Boosting'   : GradientBoostingClassifier(
        n_estimators=100, random_state=42
        # ✅ ไม่ส่ง class_weight เพราะ GB ไม่รองรับ
        #    ใช้ sample_weight ตอน .fit() แทน (ดูด้านล่าง)
    ),
    'K-Nearest Neighbors' : KNeighborsClassifier(n_neighbors=5),
}

results        = []
trained_models = {}

# ✅ ใช้ StratifiedKFold เพื่อ CV ที่แม่นยำขึ้นกับ imbalanced data
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for name, model in models.items():
    # 1. Train Model และทำ Cross-Validation
    if name == 'Gradient Boosting':
        model.fit(X_train, y_train, sample_weight=sample_weights_train)
        cv_scores = cross_val_score(
            model, X_train, y_train,
            cv=cv, scoring='f1',
            params={'sample_weight': sample_weights_train} # แก้ไขจาก fit_params เป็น params
        )
    else:
        model.fit(X_train, y_train)
        cv_scores = cross_val_score(
            model, X_train, y_train,
            cv=cv, scoring='f1'
        )

    # 2. ทำนายผลบน Test Set (จุดที่ตกหล่นไป)
    y_pred = model.predict(X_test)

    # 3. เก็บผลลัพธ์
    results.append({
        'Model'      : name,
        'Accuracy'   : accuracy_score(y_test, y_pred),
        'Precision'  : precision_score(y_test, y_pred, zero_division=0),
        'Recall'     : recall_score(y_test, y_pred, zero_division=0),
        'F1-Score'   : f1_score(y_test, y_pred, zero_division=0),
        'CV F1 Mean' : cv_scores.mean(),
        'CV F1 Std'  : cv_scores.std(),
    })
    trained_models[name] = (model, y_pred)
    print(f"   ✓ {name:<25} F1: {f1_score(y_test, y_pred, zero_division=0):.3f}  |  CV F1: {cv_scores.mean():.3f} ± {cv_scores.std():.3f}")

results_df = (
    pd.DataFrame(results)
    .sort_values('F1-Score', ascending=False)
    .reset_index(drop=True)
)

print("\n★ Model Comparison Table:")
print(results_df.round(3).to_string(index=False))

"""##**Model Comparison Visualization**"""

# print("★ Model Comparison Visualization\n")

# import matplotlib.font_manager as fm
# import seaborn as sns
# import matplotlib as mpl
# !wget -q https://github.com/Phonbopit/sarabun-webfont/raw/master/fonts/thsarabunnew-webfont.ttf

# # เพิ่มฟอนต์เข้าระบบของ Matplotlib
# fm.fontManager.addfont('thsarabunnew-webfont.ttf')

# mpl.rc('font', family='TH Sarabun New', size=14) # ปรับขนาดฟอนต์ตรงนี้ได้

# labels  = results_df['Model']
# x       = np.arange(len(labels))
# metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
# colors  = ['#ee3a8c', '#8b2252', '#c06090', '#ff82ab']
# width   = 0.18

# fig, ax = plt.subplots(figsize=(16, 7))

# for i, (metric, color) in enumerate(zip(metrics, colors)):
#     bars = ax.bar(x + (i - 1.5) * width, results_df[metric],
#                   width, label=metric, color=color, alpha=0.85, zorder=2)
#     for bar in bars:
#         h = bar.get_height()
#         ax.annotate(f'{h:.2f}',
#                     xy=(bar.get_x() + bar.get_width() / 2, h),
#                     xytext=(0, 5), textcoords='offset points',
#                     ha='center', va='bottom', fontsize=9, fontweight='bold')

# ax.set_ylabel('Scores (0.0 – 1.0)', fontsize=13)
# ax.set_title('เปรียบเทียบประสิทธิภาพ Machine Learning Models (5 โมเดล)',
#              fontsize=18, fontweight='bold', pad=20)
# ax.set_xticks(x)
# ax.set_xticklabels(labels, fontsize=12, rotation=15, ha='right')
# ax.set_ylim(0, 1.15)
# ax.legend(loc='upper right', fontsize=11)
# ax.grid(axis='y', linestyle='--', alpha=0.4, zorder=1)
# plt.tight_layout()
# plt.show()

print("\n★ Model Comparison Visualization\n")

labels  = results_df['Model']
x       = np.arange(len(labels))
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
colors  = ['#ee3a8c', '#8b2252', '#c06090', '#ff82ab']
width   = 0.18

fig, ax = plt.subplots(figsize=(16, 7))

for i, (metric, color) in enumerate(zip(metrics, colors)):
    bars = ax.bar(
        x + (i - 1.5) * width,
        results_df[metric],
        width, label=metric, color=color, alpha=0.85, zorder=2
    )
    for bar in bars:
        h = bar.get_height()
        ax.annotate(
            f'{h:.2f}',
            xy=(bar.get_x() + bar.get_width() / 2, h),
            xytext=(0, 5), textcoords='offset points',
            ha='center', va='bottom', fontsize=9, fontweight='bold'
        )

ax.set_ylabel('Scores (0.0 – 1.0)', fontsize=13)
ax.set_title('เปรียบเทียบประสิทธิภาพ Machine Learning Models (5 โมเดล)',
             fontsize=18, fontweight='bold', pad=20)
ax.set_xticks(x)
ax.set_xticklabels(labels, fontsize=12, rotation=15, ha='right')
ax.set_ylim(0, 1.15)
ax.legend(loc='upper right', fontsize=11)
ax.grid(axis='y', linestyle='--', alpha=0.4, zorder=1)
plt.tight_layout()
plt.savefig('model_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

"""##**Confusion Matrix**"""

# best_model_name = results_df.iloc[0]['Model']
# _, best_pred    = trained_models[best_model_name]

# print(f"★ STEP 5: Confusion Matrix — {best_model_name}\n")

# cm     = confusion_matrix(y_test, best_pred)
# labels_cm = np.array([
#     [f"TN\n({cm[0,0]} คน)", f"FP\n({cm[0,1]} คน)"],
#     [f"FN\n({cm[1,0]} คน)", f"TP\n({cm[1,1]} คน)"]
# ])

# fig, ax = plt.subplots(figsize=(8, 6))
# sns.heatmap(cm, annot=labels_cm, fmt='', cmap='Pastel1',
#             annot_kws={'size': 14, 'fontweight': 'bold'}, ax=ax)
# ax.set_title(f'Confusion Matrix — {best_model_name}',
#              fontsize=16, fontweight='bold', pad=15)
# ax.set_xlabel('ค่าที่ AI ทำนาย (Predicted)', fontsize=12)
# ax.set_ylabel('ข้อมูลจริง (Actual)', fontsize=12)
# ax.set_xticklabels(['Non-Target (0)', 'Winning Zone (1)'], fontsize=11)
# ax.set_yticklabels(['Non-Target (0)', 'Winning Zone (1)'], fontsize=11)
# plt.tight_layout()
# plt.show()

# print(f"\nClassification Report — {best_model_name}:")
# print(classification_report(y_test, best_pred,
#                              target_names=['Non-Target', 'Winning Zone']))

best_model_name = results_df.iloc[0]['Model']
_, best_pred    = trained_models[best_model_name]

print(f"\n★ Confusion Matrix — {best_model_name}\n")

cm        = confusion_matrix(y_test, best_pred)
labels_cm = np.array([
    [f"TN\n({cm[0,0]} คน)", f"FP\n({cm[0,1]} คน)"],
    [f"FN\n({cm[1,0]} คน)", f"TP\n({cm[1,1]} คน)"]
])

fig, ax = plt.subplots(figsize=(8, 6))
sns.heatmap(
    cm, annot=labels_cm, fmt='', cmap='Pastel1',
    annot_kws={'size': 14, 'fontweight': 'bold'}, ax=ax
)
ax.set_title(f'Confusion Matrix — {best_model_name}',
             fontsize=16, fontweight='bold', pad=15)
ax.set_xlabel('ค่าที่ AI ทำนาย (Predicted)', fontsize=12)
ax.set_ylabel('ข้อมูลจริง (Actual)', fontsize=12)
ax.set_xticklabels(['Non-Target (0)', 'Winning Zone (1)'], fontsize=11)
ax.set_yticklabels(['Non-Target (0)', 'Winning Zone (1)'], fontsize=11)
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\nClassification Report — {best_model_name}:")
print(classification_report(
    y_test, best_pred,
    target_names=['Non-Target', 'Winning Zone']
))

"""##**Feature Importance**"""

# print("★ STEP 6: Feature Importance\n")

# if 'Random Forest' in trained_models:
#     rf_model = trained_models['Random Forest'][0]
#     importances = rf_model.feature_importances_
#     fi_df = pd.DataFrame({'Feature': X_scaled.columns, 'Importance': importances})
# else:
#     lr_model = trained_models['Logistic Regression'][0]
#     importances = lr_model.coef_[0]
#     fi_df = pd.DataFrame({'Feature': X_scaled.columns, 'Importance': importances})

# fi_df = fi_df.sort_values('Importance', ascending=False).head(10).reset_index(drop=True)

# fig, ax = plt.subplots(figsize=(12, 6))
# bars = ax.barh(fi_df['Feature'][::-1], fi_df['Importance'][::-1],
#                color='#ee3a8c', alpha=0.85)
# ax.set_title('Feature Importance — ปัจจัยที่มีผลต่อการเป็น Winning Zone',
#              fontsize=16, fontweight='bold', pad=15)
# ax.set_xlabel('Importance Score', fontsize=12)
# ax.grid(axis='x', linestyle='--', alpha=0.4)
# plt.tight_layout()
# plt.show()

# print("Top Features ที่มีผลต่อ Winning Zone:")
# print(fi_df.to_string(index=False))

print("\n★ ROC Curve — ทุกโมเดล\n")

fig, ax = plt.subplots(figsize=(10, 7))
roc_colors = ['#ee3a8c', '#8b2252', '#c06090', '#ff82ab', '#d4006a']

for (name, (model, _)), color in zip(trained_models.items(), roc_colors):
    if hasattr(model, 'predict_proba'):
        y_prob = model.predict_proba(X_test)[:, 1]
    else:
        y_prob = model.decision_function(X_test)

    fpr, tpr, _ = roc_curve(y_test, y_prob)
    auc          = roc_auc_score(y_test, y_prob)
    ax.plot(fpr, tpr, color=color, lw=2, label=f'{name} (AUC = {auc:.3f})')

ax.plot([0, 1], [0, 1], 'k--', lw=1.5, label='Random Classifier')
ax.set_xlabel('False Positive Rate', fontsize=13)
ax.set_ylabel('True Positive Rate', fontsize=13)
ax.set_title('ROC Curve — เปรียบเทียบทุกโมเดล',
             fontsize=16, fontweight='bold', pad=15)
ax.legend(loc='lower right', fontsize=11)
ax.grid(linestyle='--', alpha=0.4)
plt.tight_layout()
plt.savefig('roc_curve.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n★ Feature Importance\n")

if 'Random Forest' in trained_models:
    fi_model     = trained_models['Random Forest'][0]
    importances  = fi_model.feature_importances_
    fi_label     = 'Random Forest'
elif 'Gradient Boosting' in trained_models:
    fi_model     = trained_models['Gradient Boosting'][0]
    importances  = fi_model.feature_importances_
    fi_label     = 'Gradient Boosting'
else:
    fi_model     = trained_models['Logistic Regression'][0]
    importances  = np.abs(fi_model.coef_[0])
    fi_label     = 'Logistic Regression (|coef|)'

fi_df = (
    pd.DataFrame({'Feature': X_scaled.columns, 'Importance': importances})
    .sort_values('Importance', ascending=False)
    .head(10)
    .reset_index(drop=True)
)

fig, ax = plt.subplots(figsize=(12, 6))
ax.barh(fi_df['Feature'][::-1], fi_df['Importance'][::-1],
        color='#ee3a8c', alpha=0.85)
ax.set_title(f'Feature Importance ({fi_label})\nปัจจัยที่มีผลต่อการเป็น Winning Zone',
             fontsize=16, fontweight='bold', pad=15)
ax.set_xlabel('Importance Score', fontsize=12)
ax.grid(axis='x', linestyle='--', alpha=0.4)

for i, (val, feat) in enumerate(zip(fi_df['Importance'][::-1], fi_df['Feature'][::-1])):
    ax.text(val + 0.001, i, f'{val:.3f}', va='center', fontsize=10)

plt.tight_layout()
plt.savefig('feature_importance.png', dpi=150, bbox_inches='tight')
plt.show()

print("Top 10 Features ที่มีผลต่อ Winning Zone:")
print(fi_df.to_string(index=False))

"""##**ให้เหตุผลในการเลือกโมเดลที่เหมาะสม**"""

print("★ Model Justification\n")
# print("=" * 70)

best_row = results_df.iloc[0]
print(f"★ โมเดลที่เลือก: {best_row['Model']}")
print("-" * 70)
print(f"   Accuracy  : {best_row['Accuracy']:.3f}")
print(f"   Precision : {best_row['Precision']:.3f}")
print(f"   Recall    : {best_row['Recall']:.3f}")
print(f"   F1-Score  : {best_row['F1-Score']:.3f}")
print(f"   CV F1 Mean: {best_row['CV F1 Mean']:.3f} ± {best_row['CV F1 Std']:.3f}")
# print("-" * 70)

justification = {
    'Random Forest': (
        "Random Forest ถูกเลือกเพราะ:\n"
        "  1. F1-Score สูงสุด → สมดุลระหว่าง Precision และ Recall ดีที่สุด\n"
        "  2. ทนต่อ Overfitting ด้วยการ Ensemble หลาย Decision Trees\n"
        "  3. Feature Importance อ่านได้ชัดเจน → ตีความ Business Insight ง่าย\n"
        "  4. CV F1 Std ต่ำ → ผลลัพธ์เสถียรไม่แปรปรวนตาม data split\n"
        "  5. เหมาะกับข้อมูล Survey ขนาดเล็ก (n≈63) ที่มี noise สูง"
    ),
    'Gradient Boosting': (
        "Gradient Boosting ถูกเลือกเพราะ:\n"
        "  1. F1-Score สูงสุด → แม่นยำในการจับกลุ่ม Winning Zone\n"
        "  2. เรียนรู้ pattern ซับซ้อนได้ดีกว่า Linear Model\n"
        "  3. ทนต่อ outlier ได้ดี เหมาะกับข้อมูลจาก Survey\n"
        "  4. ผลการ Cross-Validation เสถียร"
    ),
    'Logistic Regression': (
        "Logistic Regression ถูกเลือกเพราะ:\n"
        "  1. F1-Score ดีและตีความ Coefficient ได้ตรงไปตรงมา\n"
        "  2. เหมาะกับ Binary Classification และ dataset ขนาดเล็ก\n"
        "  3. ความเสี่ยง Overfitting ต่ำ\n"
        "  4. สามารถอธิบายผลลัพธ์ให้ฝ่าย Marketing เข้าใจง่าย"
    ),
    'Decision Tree': (
        "Decision Tree ถูกเลือกเพราะ:\n"
        "  1. อ่านผลลัพธ์ผ่าน Tree Diagram ได้ → Business Explainability สูง\n"
        "  2. ไม่ต้องการ Feature Scaling\n"
        "  3. เหมาะกับข้อมูล Categorical ที่แปลงแล้ว\n"
        "  4. max_depth=4 ป้องกัน Overfitting"
    ),
    'K-Nearest Neighbors': (
        "KNN ถูกเลือกเพราะ:\n"
        "  1. F1-Score สูงสุดในชุดนี้\n"
        "  2. ไม่มี Assumption เรื่อง Distribution ของข้อมูล\n"
        "  3. เหมาะกับข้อมูลที่ Feature Scaled แล้ว (MinMaxScaler)"
    ),
}

print(justification.get(best_row['Model'],
      f"  {best_row['Model']} มี F1-Score สูงสุดและ CV Score เสถียร"))

# print("\n★ ข้อเสนอแนะเชิงธุรกิจ (Business Insight):")
# # print("-" * 70)
# print("  โมเดลที่เลือกสามารถระบุกลุ่ม Winning Zone ได้แม่นยำ")
# print("  → ใช้สำหรับ Ad Targeting: ยิงโฆษณาเฉพาะกลุ่มที่ต้องการ 'อ่อนโยน+สีติดทน'")
# print("  → ลด Cost per Acquisition โดยไม่ยิงหาคนที่เน้นราคาถูกหรือความสะดวกอย่างเดียว")
# print("  → Message สำหรับกลุ่มนี้: 'อ่อนโยนต่อหนังศีรษะ สีติดนาน ดูเป็นธรรมชาติ'")
# # print("=" * 70)

print("\n★ Decision Tree Visualization\n")

dt_model = trained_models['Decision Tree'][0]

fig, ax = plt.subplots(figsize=(22, 10))
plot_tree(
    dt_model,
    feature_names=list(X_scaled.columns),
    class_names=['Non-Target', 'Winning Zone'],
    filled=True,
    rounded=True,
    fontsize=9,
    ax=ax,
    impurity=True,
    proportion=False,
)
ax.set_title('Decision Tree (max_depth=4) — เส้นทางการตัดสินใจ Winning Zone',
             fontsize=16, fontweight='bold', pad=15)
plt.tight_layout()
plt.savefig('decision_tree.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n★ Model Justification\n")

best_row = results_df.iloc[0]

print(f"★ โมเดลที่เลือก: {best_row['Model']}")
print("-" * 70)
print(f"   Accuracy  : {best_row['Accuracy']:.3f}")
print(f"   Precision : {best_row['Precision']:.3f}")
print(f"   Recall    : {best_row['Recall']:.3f}")
print(f"   F1-Score  : {best_row['F1-Score']:.3f}")
print(f"   CV F1 Mean: {best_row['CV F1 Mean']:.3f} ± {best_row['CV F1 Std']:.3f}")

justification = {
    'Random Forest': (
        "Random Forest ถูกเลือกเพราะ:\n"
        "  1. F1-Score สูงสุด → สมดุลระหว่าง Precision และ Recall ดีที่สุด\n"
        "  2. ทนต่อ Overfitting ด้วยการ Ensemble หลาย Decision Trees\n"
        "  3. Feature Importance อ่านได้ชัดเจน → ตีความ Business Insight ง่าย\n"
        "  4. CV F1 Std ต่ำ → ผลลัพธ์เสถียรไม่แปรปรวนตาม data split\n"
        "  5. เหมาะกับข้อมูล Survey ขนาดเล็ก (n=63) ที่มี noise สูง"
    ),
    'Gradient Boosting': (
        "Gradient Boosting ถูกเลือกเพราะ:\n"
        "  1. F1-Score สูงสุด → แม่นยำในการจับกลุ่ม Winning Zone\n"
        "  2. เรียนรู้ pattern ซับซ้อนได้ดีกว่า Linear Model\n"
        "  3. ทนต่อ outlier ได้ดี เหมาะกับข้อมูลจาก Survey\n"
        "  4. ผลการ Cross-Validation เสถียร (StratifiedKFold)"
    ),
    'Logistic Regression': (
        "Logistic Regression ถูกเลือกเพราะ:\n"
        "  1. F1-Score ดีและตีความ Coefficient ได้ตรงไปตรงมา\n"
        "  2. เหมาะกับ Binary Classification และ dataset ขนาดเล็ก\n"
        "  3. ความเสี่ยง Overfitting ต่ำ\n"
        "  4. สามารถอธิบายผลลัพธ์ให้ฝ่าย Marketing เข้าใจง่าย"
    ),
    'Decision Tree': (
        "Decision Tree ถูกเลือกเพราะ:\n"
        "  1. อ่านผลลัพธ์ผ่าน Tree Diagram ได้ → Business Explainability สูง\n"
        "  2. ไม่ต้องการ Feature Scaling\n"
        "  3. เหมาะกับข้อมูล Categorical ที่แปลงแล้ว\n"
        "  4. max_depth=4 ป้องกัน Overfitting"
    ),
    'K-Nearest Neighbors': (
        "KNN ถูกเลือกเพราะ:\n"
        "  1. F1-Score สูงสุดในชุดนี้\n"
        "  2. ไม่มี Assumption เรื่อง Distribution ของข้อมูล\n"
        "  3. เหมาะกับข้อมูลที่ Feature Scaled แล้ว (MinMaxScaler)"
    ),
}

print(justification.get(
    best_row['Model'],
    f"  {best_row['Model']} มี F1-Score สูงสุดและ CV Score เสถียร"
))

print("\n★ ข้อเสนอแนะเชิงธุรกิจ (Business Insight):")
print("-" * 70)
print("  โมเดลที่เลือกสามารถระบุกลุ่ม Winning Zone ได้แม่นยำ")
print("  → ใช้สำหรับ Ad Targeting: ยิงโฆษณาเฉพาะกลุ่มที่ต้องการ 'อ่อนโยน + สีติดทน'")
print("  → ลด Cost per Acquisition โดยไม่ยิงหาคนที่เน้นราคาถูกหรือความสะดวกอย่างเดียว")
print("  → Message สำหรับกลุ่มนี้: 'อ่อนโยนต่อหนังศีรษะ สีติดนาน ดูเป็นธรรมชาติ'")
print("  → ช่องทางหลัก: ซูเปอร์มาร์เก็ต / ร้านสะดวกซื้อ / ออนไลน์")
print("=" * 70)
print("★ เสร็จสิ้น Supervised Learning Pipeline")
print("=" * 70)

import joblib

# บันทึก Model ที่ดีที่สุด และ Scaler เพื่อนำไปเรียกใช้บน Web App
joblib.dump(trained_models[best_row['Model']][0], 'best_supervised_model.pkl')
joblib.dump(scaler, 'minmax_scaler.pkl')

print("★ บันทึกโมเดลและสเกลเลอร์สำเร็จ พร้อมสำหรับนำไป Deployment")