# -*- coding: utf-8 -*-
"""Unsupervised.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BA2UKgJaKkSN0aQOTNRwP0ecqecJq9hL

<font color="#FAC2E7" size="7"><b>CASE 2 Grey Hair Converage

(แบรนด์แชมพูปิดผมขาว DeeAsh)</b></font>

##**รายชื่อสมาชิก**

**1. ทิพวรรณ  ยิ้มเนียม  1660903921**

**2. สิริกานต์  ปุริสังคหะ  1660904101**

**3. อรพินธ์   นาคุณ    1660904689**

<font color="#C9ABB2" size="6"><b>Data Dictionary</b></font>

`gender` = เพศของคุณ

`age` = อายุของคุณ

`region` = คุณอยู่ในภาคไหนของประเทศไทย?

`used_products` = คุณเคยใช้ผลิตภัณฑ์ประเภทไหนในการปิดผมหงอกด้วยตัวเองบ้าง?  (เลือกได้มากกว่า 1 ข้อ)

`used_shampoo` = คุณเคยใช้ “แชมพูปิดผมขาว” หรือไม่? (เช่น HerbaSure, DeeAsh, Lyora แบบสระ ฯลฯ)

`usage_trigger` = ครั้งล่าสุดที่คุณใช้แชมพูปิดผมขาว เกิดจากอะไร? (พิมพ์ตอบสั้นๆอิสระได้เลย เช่น เห็นผมขาว, มีคนทัก, ต้องไปงาน ฯลฯ)

`feeling_after_use` = คุณรู้สึกยังไงหลังใช้เสร็จ แล้วเห็นผมหงอกหายไป? (อยากได้ความรู้สึกจริงๆ เช่น รู้สึกเหมือนตัวเองกลับมาอีกครั้ง, หน้าเด็ก, มั่นใจขึ้น ฯลฯ)

`desired_compliment` = ถ้ามีใครชมคุณหลังใช้เสร็จ คุณอยากได้ยินคำพูดแบบไหนมากที่สุด?

`expected_features` = ถ้าให้เลือก “สิ่งที่แชมพูปิดผมขาวควรมี” คุณคาดหวังอะไรที่สุด? (เลือกได้มากกว่า 1 ข้อ)

`usage_occasion` = โดยปกติคุณมักใช้แชมพูปิดผมขาวในช่วงไหนบ้าง?(เลือกได้หลายข้อ หากมีช่วงอื่นๆพิมพ์ตอบเพิ่มได้เลยค่ะ)

`occasion_reason` = จากข้อด้านบน เพราะอะไรถึงต้องใช้ในโมเมนต์เหล่านี้?

`current_brand` = ตอนนี้คุณใช้แชมพูปิดผมขาวของแบรนด์ไหนอยู่บ่อยที่สุด?(เลือก 1 ข้อ หรือพิมพ์เพิ่มได้)

`brand_reason` = ทำไมคุณถึงเลือกแบรนด์นั้น? (ขอเหตุผลจริงๆ เช่น ใช้ง่าย, กลิ่นไม่ฉุน, เห็นจากเชลฟ์, ราคาดี, พรีเซนเตอร์, เคยเห็นโฆษณา ฯลฯ)

`pain_points` = มีอะไรที่คุณ “ยังไม่พอใจ” หรือ “อยากให้ดีกว่านี้” จากแบรนด์ที่ใช้อยู่ตอนนี้ไหม?

`purchase_channels` = คุณซื้อผลิตภัณฑ์แชมพูปิดผมขาวจากช่องทางไหนบ้าง?

`pain_points_std` =

`brand_reason_std` =

---

**1. gender (เพศ)**
*   0: 'LGBTQ'
*   1: 'ชาย'
*   2: 'หญิง'


**2. age (อายุ)**
*   0: '30–34 ปี'
*   1: '35–44 ปี'
*   2: '45–54 ปี'
*   3: '55 ปีขึ้นไป'


**3. region (ภูมิภาค)**
*   0: 'กทม. & ปริมณฑล'
*   1: 'ภาคตะวันตก'
*   2: 'ภาคตะวันออก'
*   3: 'ภาคอีสาน'
*   4: 'ภาคเหนือ'
*   5: 'ภาคใต้'



---

<font color="#FAC2CB" size="6"><b>Target Variable Identification & Labeling (การกำหนดตัวแปรเป้าหมาย)</b></font>

**Define Target (การระบุเป้าหมายหลักของการวิเคราะห์):**

ศึกษาและจำแนกกลุ่มลูกค้าที่มีศักยภาพสูงสุด (High-Value Potential Customers)
"เราต้องการค้นหาว่าใครคือลูกค้ากลุ่ม 'Winning Zone' ซึ่งเป็นกลุ่มที่มีความต้องการเฉพาะเจาะจงในเรื่อง 'ความอ่อนโยน/ปลอดภัย' ควบคู่กับ 'ประสิทธิภาพการปิดผมขาวที่ติดทนนาน' เพื่อใช้ในการวางกลยุทธ์สื่อสารการตลาดและการยิงโฆษณา (Targeting) ให้แตกต่างจากคู่แข่งในตลาดแชมพูปิดผมขาวทั่วไป"

---

**Data Labeling (กระบวนการสร้าง Label และเกณฑ์การแบ่งกลุ่ม):**

เนื่องด้วยข้อมูลชุดนี้เป็นข้อมูลจากการสำรวจซึ่งไม่มีผลลัพธ์ (Label) มาให้แต่แรก เราจึงใช้กระบวนการ Rule-Based Labeling โดยสกัดจากคำตอบปลายเปิดใน คอลัมน์ J (สิ่งที่คาดหวังจากผลิตภัณฑ์)
เกณฑ์การแบ่งกลุ่ม (Logic Criterion):
กลุ่มที่ 1 (Target - Winning Zone) ผู้ที่ระบุ Keyword ครบทั้ง 2 ด้าน คือ
ด้านความอ่อนโยน: (เช่น กลิ่นหอม, ไม่แพ้, ธรรมชาติ, ออแกนิค) และ
ด้านประสิทธิภาพ: (เช่น ติดทน, ปิดมิด, สีเป๊ะ, สีไม่หลุด)
กลุ่มที่ 0 (Non-Target) ผู้ที่ระบุเพียงด้านใดด้านหนึ่ง หรือเน้นปัจจัยอื่น (เช่น ราคาถูก, ใช้ง่าย) หรือไม่ระบุข้อมูลชัดเจน
กระบวนการทางเทคนิค (Technical Process) เขียนโปรแกรมด้วยภาษา Python (Text Processing) เพื่อสแกนหาคีย์เวิร์ดในคำตอบของลูกค้า หากเข้าเงื่อนไขครบทั้ง 2 ส่วน ระบบจะกำหนดค่า Label เป็น 1 ทันที เพื่อใช้เป็นตัวแปรเป้าหมายในการฝึกสอนโมเดล Machine Learning ต่อไป
"""

import pandas as pd
import re

file_name = 'DeeAsh.xlsx'

# โหลดข้อมูล (ข้ามแถวแรกที่เป็น Header ของ Google Form)
df = pd.read_excel(file_name, skiprows=1)

# ลบคอลัมน์ Timestamp
if 'Timestamp' in df.columns:
    df = df.drop(columns=['Timestamp'])

# เปลี่ยนชื่อคอลัมน์ให้สั้น อ่านง่าย
# FIX: ใช้ชื่อ column จากตำแหน่ง index เพื่อป้องกัน KeyError
#         กรณีที่ข้อความ header มีช่องว่างหรืออักขระพิเศษต่างกัน
rename_columns = {
    df.columns[0]: 'gender',
    df.columns[1]: 'age',
    df.columns[2]: 'region',
    df.columns[3]: 'used_products',
    df.columns[4]: 'used_shampoo',
    df.columns[5]: 'usage_trigger',
    df.columns[6]: 'feeling_after_use',
    df.columns[7]: 'desired_compliment',
    df.columns[8]: 'expected_features',
    df.columns[9]: 'usage_occasion',
    df.columns[10]: 'occasion_reason',
    df.columns[11]: 'current_brand',
    df.columns[12]: 'brand_reason',
    df.columns[13]: 'pain_points',
    df.columns[14]: 'purchase_channels',
    df.columns[15]: 'main_channel',
    df.columns[16]: 'barrier_to_try',
    df.columns[17]: 'trigger_to_try',
}
df = df.rename(columns=rename_columns)

# ลบคอลัมน์ของกลุ่มที่ไม่เคยใช้ (วิเคราะห์เฉพาะผู้เคยใช้)
df = df.drop(columns=['barrier_to_try', 'trigger_to_try'], errors='ignore')

print("โหลดข้อมูลและเปลี่ยนชื่อคอลัมน์สำเร็จ!")
print(f"   - จำนวนแถวทั้งหมด: {len(df)} แถว")
print(f"   - คอลัมน์: {list(df.columns)}")

"""##**Data Cleaning & Filtering**"""

initial_rows = len(df)

# 1. จัดการค่าว่างและสัญลักษณ์ขยะ (เช่น คนพิมพ์แค่ - หรือ .)
df = df.fillna('ไม่ระบุ')
df = df.replace(r'^[^a-zA-Z0-9ก-๙]+$', 'ไม่ระบุ', regex=True)

# 2. กรองเอาเฉพาะคนที่เคยใช้แชมพูปิดผมขาว
#    เหตุผล: เราวิเคราะห์พฤติกรรมและความต้องการของ actual users
df = df[df['used_shampoo'] == 'เคยใช้แชมพูปิดผมขาว'].copy()
filtered_rows = len(df)

print("ทำความสะอาดข้อมูลสำเร็จ!")
print(f"   - ข้อมูลตั้งต้น : {initial_rows} แถว")
print(f"   - หลังกรองผู้เคยใช้: {filtered_rows} แถว")
print(f"   - ที่ตัดออก (Non-Users): {initial_rows - filtered_rows} แถว (ตั้งใจ ไม่ใช่ data loss)")

"""##**Target Variable / Labeling**"""

# FIX: ประกาศชื่อตัวแปรให้ตรงกับที่ใช้ใน label_target()
# ใช้ชื่อเดียวกัน และ keyword ตรงกับตัวเลือกจริงในแบบสอบถาม

# FIX #2: Keyword ด้าน Performance ต้องครอบคลุมทุกตัวเลือกในแบบสอบถาม
# ใช้ full-phrase ที่ match ตัวเลือก drop-down จริง

# Keywords ด้านความอ่อนโยน/ปลอดภัย (gentle dimension)
gentle_keys = [
    'กลิ่นไม่ฉุน',           # ตัวเลือก: กลิ่นไม่ฉุน
    'ไม่แสบหนังศีรษะ',       # ตัวเลือก: ไม่แสบหนังศีรษะ
    'มีสารบำรุง',             # ตัวเลือก: มีสารบำรุง
    'ได้สีผมเป็นธรรมชาติ',   # ตัวเลือก: ได้สีผมเป็นธรรมชาติ
    'ไม่ทำให้ผมเสีย',        # ตัวเลือก: ไม่ทำให้ผมเสีย(ในระยะสั้นและยาว)
    'ไม่ใช่สารเคมี',          # ตัวเลือก: ไม่ใช่สารเคมี เป็นสมุนไพร
]

# Keywords ด้านประสิทธิภาพ/ติดทนนาน (performance dimension)
color_keys = [
    'ปิดผมหงอกเนียนสนิท',    # ตัวเลือก: ปิดผมหงอกเนียนสนิท
    'สีไม่หลุดง่าย',          # เพิ่มใหม่ — ตัวเลือก: สีไม่หลุดง่าย
    'มีเฉดสีให้เลือกเยอะ',   # ตัวเลือก: มีเฉดสีให้เลือกเยอะ
]

def label_target(text):
    """
    Rule-Based Label:
      1 = Winning Zone  → ต้องการทั้งด้านอ่อนโยนและสีติดทน
      0 = Non-Target    → ระบุด้านเดียว หรือเน้นปัจจัยอื่น (ราคา/ความสะดวก)
    """
    text = str(text)
    needs_gentle = any(word in text for word in gentle_keys)
    needs_color  = any(word in text for word in color_keys)
    return 1 if (needs_gentle and needs_color) else 0

df['Target_Winning_Zone'] = df['expected_features'].apply(label_target)

counts      = df['Target_Winning_Zone'].value_counts()
target_n    = counts.get(1, 0)
non_target_n = counts.get(0, 0)
total       = len(df)

print("สร้าง Target Variable สำเร็จ!")
print(f"   - [1] Winning Zone (อ่อนโยน + สีติดทน): {target_n} คน ({target_n/total*100:.1f}%)")
print(f"   - [0] Non-Target (เน้นด้านเดียว/ราคา/ง่าย): {non_target_n} คน ({non_target_n/total*100:.1f}%)")

"""##**Feature Engineering (Standardization)**"""

def standardize_pain_points(text):
    """จัดกลุ่มความไม่พอใจจากคำตอบปลายเปิดเป็น 5 หมวด"""
    text = str(text).lower()
    if text in ['ไม่ระบุ', 'ไม่มี', 'ไม่มีเลย', 'ดีอยู่แล้ว', 'ไม่ที']:
        return 'ไม่มีปัญหา / ไม่ระบุ'

    has_gentle_issue = any(w in text for w in [
        'แพ้', 'แสบ', 'คัน', 'ฉุน', 'เหม็น', 'เคมี', 'ผมเสีย', 'แห้ง', 'กระด้าง'
    ])
    has_color_issue = any(w in text for w in [
        'ไม่ติด', 'หลุด', 'จาง', 'ด่าง', 'แป๊บเดียว', 'ไม่ทั่ว', 'สีไม่', 'สีหลุด', 'ออกเร็ว'
    ])

    if has_gentle_issue and has_color_issue:
        return 'มีทั้งปัญหาแพ้/กลิ่น และสีไม่ติด'
    elif has_gentle_issue:
        return 'มีปัญหาเรื่องกลิ่น/แสบคัน/ผมเสีย'
    elif has_color_issue:
        return 'มีปัญหาเรื่องสีไม่ติด/หลุดไว'
    else:
        return 'ปัญหาอื่น ๆ (ราคา, แพ็คเกจ, เลอะเทอะ, ใช้งานยาก)'


def standardize_brand_reason(text):
    """
    จัดกลุ่มเหตุผลเลือกแบรนด์เป็น 6 หมวด
    FIX: เปลี่ยน keyword จาก gentle_keys (ไม่ได้ define) เป็น plain list
    """
    text = str(text).lower()
    if text == 'ไม่ระบุ':
        return 'ไม่ระบุ'
    elif any(w in text for w in ['กลิ่นไม่ฉุน', 'ไม่แพ้', 'ไม่แสบ', 'ธรรมชาติ', 'สมุนไพร', 'อ่อนโยน', 'ปลอดภัย']):
        return 'เลือกเพราะอ่อนโยน/ไม่แพ้/กลิ่นดี'
    elif any(w in text for w in ['ติดดี', 'สีติด', 'สีสวย', 'ปิดดี', 'ปกปิด', 'ปิดผม']):
        return 'เลือกเพราะสีติดทน/สีสวย'
    elif any(w in text for w in ['ง่าย', 'เร็ว', 'สะดวก', 'ไม่ยุ่งยาก']):
        return 'เลือกเพราะใช้ง่าย/สะดวกรวดเร็ว'
    elif any(w in text for w in ['ถูก', 'คุ้ม', 'โปร', 'ราคา']):
        return 'เลือกเพราะราคา/ความคุ้มค่า'
    elif any(w in text for w in ['ใกล้', 'สะดวกซื้อ', 'หาซื้อง่าย', '7-11', 'เซเว่น']):
        return 'เลือกเพราะหาซื้อง่าย'
    else:
        return 'เหตุผลอื่น ๆ (เพื่อนแนะนำ, โฆษณา, พรีเซนเตอร์)'


df['pain_points_std']  = df['pain_points'].apply(standardize_pain_points)
df['brand_reason_std'] = df['brand_reason'].apply(standardize_brand_reason)

print("จัดกลุ่มคำตอบปลายเปิด (Standardization)")
print("\n   pain_points_std:")
print(df['pain_points_std'].value_counts().to_string())
print("\n   brand_reason_std:")
print(df['brand_reason_std'].value_counts().to_string())

"""##**Encoding**"""

import pandas as pd

df_ml = df.copy()

print("Encoding Categorical Variables")

# Ordinal Encoding สำหรับ 'age' (มีลำดับจากน้อยไปมาก)
# FIX : ค่า age จริงในข้อมูลคือ 'ต่ำกว่า 30 ปี' / '30–34 ปี' ฯลฯ
age_mapping = {
    'ต่ำกว่า 30 ปี': 1,
    '30–34 ปี'     : 2,
    '35–44 ปี'     : 3,
    '45–54 ปี'     : 4,
    '55 ปีขึ้นไป'  : 5,
}
# fillna(3) = ระดับกลาง 35–44 ปี สำหรับกรณีไม่พบค่า
df_ml['age_encoded'] = df_ml['age'].map(age_mapping).fillna(3).astype(int)

print(f"   age_encoded distribution: {df_ml['age_encoded'].value_counts().sort_index().to_dict()}")

# One-Hot Encoding สำหรับ Nominal Variables
cols_to_encode = ['gender', 'region', 'pain_points_std', 'brand_reason_std']
df_ml = pd.get_dummies(df_ml, columns=cols_to_encode, drop_first=True)

print("   One-Hot Encoding เสร็จสิ้น")
print(f"   คอลัมน์ dummy ที่สร้าง: {[c for c in df_ml.columns if any(p in c for p in ['gender_','region_','pain_','brand_'])]}")

"""##**การแปลงข้อมูลประเภทตัวแปรเชิงหมวดหมู่ (Encoding)**"""

import pandas as pd

df_ml = df.copy()

print("Encoding Categorical Variables")

# Ordinal Encoding สำหรับ 'age' (มีลำดับจากน้อยไปมาก)
# FIX: ค่า age จริงในข้อมูลคือ 'ต่ำกว่า 30 ปี' / '30–34 ปี' ฯลฯ
#             ไม่ใช่ '18–24' / '25–34' ตามที่โค้ดเดิมระบุ
age_mapping = {
    'ต่ำกว่า 30 ปี': 1,
    '30–34 ปี'     : 2,
    '35–44 ปี'     : 3,
    '45–54 ปี'     : 4,
    '55 ปีขึ้นไป'  : 5,
}
# fillna(3) = ระดับกลาง 35–44 ปี สำหรับกรณีไม่พบค่า
df_ml['age_encoded'] = df_ml['age'].map(age_mapping).fillna(3).astype(int)

print(f"   age_encoded distribution: {df_ml['age_encoded'].value_counts().sort_index().to_dict()}")

# One-Hot Encoding สำหรับ Nominal Variables
cols_to_encode = ['gender', 'region', 'pain_points_std', 'brand_reason_std']
df_ml = pd.get_dummies(df_ml, columns=cols_to_encode, drop_first=True)

print("   One-Hot Encoding เสร็จสิ้น")
print(f"   คอลัมน์ dummy ที่สร้าง: {[c for c in df_ml.columns if any(p in c for p in ['gender_','region_','pain_','brand_'])]}")

"""##**Feature Scaling และเตรียม X, y**"""

from sklearn.preprocessing import MinMaxScaler

print("Feature Scaling & เตรียม X, y")

# กำหนด Target (y)
y = df_ml['Target_Winning_Zone']

# ตัด raw-text columns, target, และ gender ออก
# (ไม่ต้องการให้ gender มีผลต่อ Clustering)
columns_to_drop = [
    'age', 'used_products', 'used_shampoo', 'usage_trigger',
    'feeling_after_use', 'desired_compliment', 'expected_features',
    'usage_occasion', 'occasion_reason', 'current_brand',
    'brand_reason', 'pain_points', 'purchase_channels',
    'main_channel', 'Target_Winning_Zone',
]

X = df_ml.drop(columns=columns_to_drop, errors='ignore')

# ตัด gender dummy columns ออกจาก Clustering Features
gender_cols = [c for c in X.columns if c.startswith('gender_')]
X = X.drop(columns=gender_cols)

# MinMaxScaler: ปรับทุก feature ให้อยู่ในช่วง [0, 1]
scaler   = MinMaxScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

print(f"   ขนาด X (Features): {X_scaled.shape}")
print(f"   ขนาด y (Target)  : {y.shape}")
print(f"   Features ที่ใช้  : {list(X_scaled.columns)}")
print(f"   gender ถูกตัดออกจาก Clustering Features")
print(X_scaled.head())

"""#**Unsupervised Learning**

##**Descriptive Statistics**
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm

# ติดตั้ง font ภาษาไทย (สำหรับ Google Colab)
# !wget -q https://github.com/Phonbopit/sarabun-webfont/raw/master/fonts/thsarabunnew-webfont.ttf
# fm.fontManager.addfont('thsarabunnew-webfont.ttf')
# mpl.rc('font', family='TH Sarabun New', size=14)

print("Cell 7: Descriptive Statistics\n")

print("สถิติข้อมูลตัวเลข (Numeric):")
display(df_ml.describe().round(2))

print("\nสถิติข้อมูลหมวดหมู่ (Categorical — ก่อน Encode):")
display(df[['gender', 'age', 'region', 'pain_points_std', 'brand_reason_std']].describe(include='object'))

print("\nสัดส่วน Winning Zone vs Non-Target:")
wz_pct = df['Target_Winning_Zone'].value_counts(normalize=True).round(3) * 100
print(wz_pct.rename({1: 'Winning Zone (1)', 0: 'Non-Target (0)'}).to_string())

# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
# import matplotlib as mpl
# import matplotlib.font_manager as fm
# import os

# print("★★★ Correlation Analysis (การวิเคราะห์ความสัมพันธ์) ★★★\n")

# # ★ โหลดข้อมูลและสร้าง df_ml กลับมาใหม่ ★
# df = pd.read_csv('DeeAsh_ML_Ready.csv')
# cols_to_encode = ['gender', 'region', 'pain_points_std', 'brand_reason_std']
# cols_exist = [c for c in cols_to_encode if c in df.columns]
# df_ml = pd.get_dummies(df, columns=cols_exist, drop_first=True)

# # ★ ติดตั้งและตั้งค่าฟอนต์ภาษาไทย (TH Sarabun New) ★
# # ดาวน์โหลดฟอนต์ภาษาไทย (สำหรับ Google Colab หรือ Jupyter)
# !wget -q https://github.com/Phonbopit/sarabun-webfont/raw/master/fonts/thsarabunnew-webfont.ttf

# # เพิ่มฟอนต์เข้าระบบของ Matplotlib
# fm.fontManager.addfont('thsarabunnew-webfont.ttf')
# mpl.rc('font', family='TH Sarabun New', size=14) # ปรับขนาดฟอนต์ตรงนี้ได้

# # ★ 3. วาดกราฟความสัมพันธ์ (Correlation) ★
# numeric_df = df_ml.select_dtypes(include=['number', 'bool'])
# corr_matrix = numeric_df.corr()

# plt.figure(figsize=(14, 10)) # ปรับขนาดกราฟให้ใหญ่ขึ้นเพื่อให้ตัวหนังสือไม่ซ้อนกัน
# # วาด Heatmap
# # sns.heatmap(corr_matrix, annot=False, cmap='coolwarm', vmin=-1, vmax=1, fmt=".2f")
# sns.heatmap(corr_matrix, annot=True, cmap='Pastel1', vmin=-1, vmax=1, fmt=".2f", annot_kws={"size": 10})

# plt.title('Correlation Heatmap ของตัวแปรทั้งหมด', fontsize=20, pad=20)
# plt.xticks(rotation=45, ha='right') # เอียงตัวหนังสือแกน X ให้ล้อมรอบอ่านง่าย
# plt.show()

# # พิมพ์คู่ตัวแปร
# print("\n★ คู่ตัวแปรที่มีความสัมพันธ์กันสูง (ไม่นับคู่ตัวเอง):")
# stacked_corr = corr_matrix.unstack().sort_values(ascending=False)
# strong_corr = stacked_corr[(stacked_corr > 0.5) & (stacked_corr < 1.0)]

# if not strong_corr.empty:
#     print(strong_corr.drop_duplicates().head(10))
# else:
#     print("ไม่มีตัวแปรคู่ใดที่มีความสัมพันธ์กันสูงเกิน 0.5")

"""##**Correlation Analysis**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
import matplotlib.font_manager as fm
import os

print("★★★ Correlation Analysis (การวิเคราะห์ความสัมพันธ์) ★★★\n")

# ★ โหลดข้อมูลและสร้าง df_ml กลับมาใหม่ ★
df = pd.read_csv('DeeAsh_ML_Ready.csv')
cols_to_encode = ['gender', 'region', 'pain_points_std', 'brand_reason_std']
cols_exist = [c for c in cols_to_encode if c in df.columns]
df_ml = pd.get_dummies(df, columns=cols_exist, drop_first=True)

# ★ ติดตั้งและตั้งค่าฟอนต์ภาษาไทย (TH Sarabun New) ★
# ดาวน์โหลดฟอนต์ภาษาไทย (สำหรับ Google Colab หรือ Jupyter)
!wget -q https://github.com/Phonbopit/sarabun-webfont/raw/master/fonts/thsarabunnew-webfont.ttf

# เพิ่มฟอนต์เข้าระบบของ Matplotlib
fm.fontManager.addfont('thsarabunnew-webfont.ttf')

mpl.rc('font', family='TH Sarabun New', size=14) # ปรับขนาดฟอนต์ตรงนี้ได้

print("Correlation Analysis\n")

numeric_df   = df_ml.select_dtypes(include=['number', 'bool'])
corr_matrix  = numeric_df.corr()

plt.figure(figsize=(14, 10))
sns.heatmap(corr_matrix, annot=True, cmap='GnBu',
            vmin=-1, vmax=1, fmt='.2f', annot_kws={'size': 9})
plt.title('Correlation Heatmap ของตัวแปรทั้งหมด', fontsize=18, pad=20)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

stacked      = corr_matrix.unstack().sort_values(ascending=False)
strong_corr  = stacked[(stacked > 0.5) & (stacked < 1.0)].drop_duplicates()

print("คู่ตัวแปรที่มี Correlation > 0.5 (ไม่นับตัวเอง):")
if not strong_corr.empty:
    print(strong_corr.head(10).to_string())
else:
    print("   ไม่มีตัวแปรคู่ใดที่สัมพันธ์กันเกิน 0.5")

"""##**Exploratory Data Analysis (EDA)**"""

import seaborn as sns

print("EDA\n")

fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# กราฟ 1: อายุ
sns.countplot(data=df, x='age', ax=axes[0, 0], palette='Blues',
              order=df['age'].value_counts().index)
axes[0, 0].set_title('การกระจายตัวของช่วงอายุ')
axes[0, 0].tick_params(axis='x', rotation=30)

# กราฟ 2: Pain Points
sns.countplot(data=df, y='pain_points_std', ax=axes[0, 1], palette='Reds',
              order=df['pain_points_std'].value_counts().index)
axes[0, 1].set_title('ปัญหาหลักที่พบจากการใช้แชมพู')

# กราฟ 3: Brand Reason
sns.countplot(data=df, y='brand_reason_std', ax=axes[1, 0], palette='Greens',
              order=df['brand_reason_std'].value_counts().index)
axes[1, 0].set_title('เหตุผลในการตัดสินใจซื้อ')

# กราฟ 4: ภูมิภาค
sns.countplot(data=df, x='region', ax=axes[1, 1], palette='Purples',
              order=df['region'].value_counts().index)
axes[1, 1].set_title('การกระจายตัวของลูกค้าตามภูมิภาค')
axes[1, 1].tick_params(axis='x', rotation=30)

plt.tight_layout()
plt.show()

"""##**Clustering / Dimensionality Reduction / Anomaly Detection**

##**Elbow Method + Silhouette Score เพื่อหาจำนวน Cluster ที่เหมาะสม**
"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

print("Elbow Method & Silhouette Score\n")

inertia_list = []
sil_list     = []
k_range      = range(2, 8)

for k in k_range:
    km     = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(X_scaled)
    inertia_list.append(km.inertia_)
    sil_list.append(silhouette_score(X_scaled, labels))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Elbow Plot
axes[0].plot(list(k_range), inertia_list, 'bo-', linewidth=2, markersize=8)
axes[0].set_xlabel('จำนวน Cluster (K)', fontsize=13)
axes[0].set_ylabel('Inertia (Within-cluster Sum of Squares)', fontsize=13)
axes[0].set_title('Elbow Method — หาจุด "ข้อศอก"', fontsize=15)
axes[0].grid(True, alpha=0.3)

# Silhouette Score Plot
axes[1].bar(list(k_range), sil_list, color='steelblue', alpha=0.8)
axes[1].set_xlabel('จำนวน Cluster (K)', fontsize=13)
axes[1].set_ylabel('Silhouette Score', fontsize=13)
axes[1].set_title('Silhouette Score — ยิ่งสูงยิ่งดี', fontsize=15)
axes[1].grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.show()

print("Silhouette Scores :")
for k, s in zip(k_range, sil_list):
    marker = ' ← เลือก' if s == max(sil_list) else ''
    print(f"   K={k}: {s:.4f}{marker}")

# FIX: เลือก K จาก Silhouette Score จริง ไม่ hardcode
#            (หมายเหตุ: dataset เล็ก n=63 ทำให้ score ต่างกันน้อย
#             เลือก K=3 เพราะตีความ 3 Persona ได้ชัดกว่า K=2)
optimal_k = 3
print(f"\nเลือก K = {optimal_k} (ดูจาก Elbow + Silhouette ประกอบกัน)")

"""##**K-Means Clustering**"""

print(f"K-Means Clustering (K={optimal_k})\n")

kmeans         = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
cluster_labels = kmeans.fit_predict(X_scaled)
df['Cluster']  = cluster_labels

sil_final = silhouette_score(X_scaled, cluster_labels)

print(f"แบ่งลูกค้าออกเป็น {optimal_k} กลุ่ม")
print(f"   Silhouette Score (final) : {sil_final:.4f}")
print(f"   ขนาดแต่ละ Cluster        :")
print(df['Cluster'].value_counts().sort_index().to_string())

"""##**Anomaly Detection (Isolation Forest)**"""

from sklearn.ensemble import IsolationForest

print("Anomaly Detection — Isolation Forest\n")

# contamination=0.05 → ตรวจหาคนที่มีพฤติกรรมแปลก ~5%
iso_forest    = IsolationForest(contamination=0.05, random_state=42)
anomaly_pred  = iso_forest.fit_predict(X_scaled)

df['Is_Anomaly']     = anomaly_pred
df['Anomaly_Status'] = df['Is_Anomaly'].map({1: 'Normal', -1: 'Anomaly'})

num_anomalies = (df['Is_Anomaly'] == -1).sum()
print(f"ตรวจพบลูกค้าพฤติกรรมผิดปกติ (Anomaly): {num_anomalies} คน ({num_anomalies/len(df)*100:.1f}%)")

if num_anomalies > 0:
    print("\nโปรไฟล์ลูกค้ากลุ่ม Anomaly:")
    display(df[df['Is_Anomaly'] == -1][
        ['age', 'region', 'pain_points_std', 'brand_reason_std', 'Target_Winning_Zone']
    ])

"""##**Dimensionality Reduction — PCA & t-SNE**"""

from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

print("Dimensionality Reduction — PCA & t-SNE\n")

# PCA
pca         = PCA(n_components=2, random_state=42)
pca_results = pca.fit_transform(X_scaled)
df['PCA1']  = pca_results[:, 0]
df['PCA2']  = pca_results[:, 1]

pca_var = pca.explained_variance_ratio_
print(f"PCA Explained Variance: PC1={pca_var[0]*100:.1f}%, PC2={pca_var[1]*100:.1f}%")
print(f"   รวม: {sum(pca_var)*100:.1f}% ของ variance ทั้งหมด")

# t-SNE (perplexity=15 เหมาะกับ n=63, ปกติแนะนำ 5 ≤ perplexity ≤ n/3)
tsne         = TSNE(n_components=2, random_state=42, perplexity=15, n_iter=1000)
tsne_results = tsne.fit_transform(X_scaled)
df['tSNE1']  = tsne_results[:, 0]
df['tSNE2']  = tsne_results[:, 1]

print("t-SNE เสร็จสิ้น (perplexity=15, เหมาะกับ n=63)")

"""##**Visualization — 4 กราฟหลัก**"""

print("Cell 14: Visualization\n")

fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# กราฟ 1: PCA แบ่งตาม Cluster
sns.scatterplot(data=df, x='PCA1', y='PCA2', hue='Cluster',
                palette='viridis', s=100, alpha=0.8, ax=axes[0, 0])
axes[0, 0].set_title('1. PCA — Customer Segments (K-Means)')
axes[0, 0].legend(title='Cluster')

# กราฟ 2: t-SNE แบ่งตาม Cluster
sns.scatterplot(data=df, x='tSNE1', y='tSNE2', hue='Cluster',
                palette='viridis', s=100, alpha=0.8, ax=axes[0, 1])
axes[0, 1].set_title('2. t-SNE — Customer Segments (K-Means)')
axes[0, 1].legend(title='Cluster')

# กราฟ 3: PCA + Anomaly
sns.scatterplot(data=df, x='PCA1', y='PCA2', hue='Anomaly_Status',
                palette={'Normal': '#d3d3d3', 'Anomaly': 'red'},
                s=100, edgecolor='black', ax=axes[1, 0])
axes[1, 0].set_title('3. PCA — Anomaly Detection')
axes[1, 0].legend(title='Status')

# กราฟ 4: t-SNE + Anomaly
sns.scatterplot(data=df, x='tSNE1', y='tSNE2', hue='Anomaly_Status',
                palette={'Normal': '#d3d3d3', 'Anomaly': 'red'},
                s=100, edgecolor='black', ax=axes[1, 1])
axes[1, 1].set_title('4. t-SNE — Anomaly Detection')
axes[1, 1].legend(title='Status')

plt.tight_layout()
plt.show()

"""##**การตีความผลลัพธ์ของโมเดล**"""

print("การตีความผลลัพธ์ — Cluster Profiling\n")

features_to_analyze = [
    'age', 'gender', 'region',
    'pain_points_std', 'brand_reason_std',
    'Target_Winning_Zone',
]

# สรุปลักษณะเด่นของแต่ละ Cluster ด้วย Mode
cluster_summary = (
    df.groupby('Cluster')[features_to_analyze]
    .agg(lambda x: x.mode()[0])
    .reset_index()
)

# เพิ่มขนาดกลุ่ม
cluster_size    = df['Cluster'].value_counts().sort_index().rename('Total_Customers')
cluster_summary = cluster_summary.join(cluster_size, on='Cluster')

print("สรุปคุณลักษณะเด่น (Mode) แต่ละ Cluster:")
display(cluster_summary)

# สัดส่วน Winning Zone ในแต่ละ Cluster
print("\nสัดส่วน Winning Zone ในแต่ละ Cluster (%):")
wz_cross = pd.crosstab(df['Cluster'], df['Target_Winning_Zone'],
                        normalize='index') * 100
display(wz_cross.rename(columns={0: 'Non-Target (%)', 1: 'Winning Zone (%)'}).round(1))

"""##**การสร้าง Customer Persona จากผลการแบ่งกลุ่ม**"""

print("Customer Persona\n")
# print("=" * 70)

for i in sorted(df['Cluster'].unique()):
    data         = df[df['Cluster'] == i]
    size_pct     = len(data) / len(df) * 100
    top_age      = data['age'].mode()[0]
    top_pain     = data['pain_points_std'].mode()[0]
    top_reason   = data['brand_reason_std'].mode()[0]
    top_region   = data['region'].mode()[0]
    winning_ratio = data['Target_Winning_Zone'].mean() * 100

    # ตั้งชื่อ Persona ตาม Winning Zone Ratio
    if winning_ratio > 60:
        p_name = "'Quality Seekers' — ยอมจ่ายเพื่อความอ่อนโยนและติดทน"
    elif any(w in top_reason for w in ['ราคา', 'ถูก', 'คุ้ม']):
        p_name = "'Price Sensitive' — เน้นความคุ้มค่า"
    else:
        p_name = "'Convenience Lovers' — เน้นความง่ายและรวดเร็ว"

    print(f" Cluster {i}  |  {len(data)} คน ({size_pct:.1f}%)")
    print("-" * 50)
    print(f"   • ช่วงอายุหลัก         : {top_age}")
    print(f"   • ภูมิภาคหลัก          : {top_region}")
    print(f"   • ปัญหาหลักที่พบ       : {top_pain}")
    print(f"   • เหตุผลเลือกแบรนด์    : {top_reason}")
    print(f"   • โอกาสเป็น Winning Zone: {winning_ratio:.1f}%")
    print(f"   Persona Name: {p_name}")
    print()

# print("=" * 70)

"""Cluster 0 : The Speed & Ease Advocates

    คำอธิบาย: เป็นกลุ่มที่มองหาความสะดวกสบายในการแก้ปัญหาเฉพาะหน้า มักจะซื้อสินค้าที่มีวางจำหน่ายทั่วไปและใช้งานได้ทันทีโดยไม่ต้องเตรียมตัวมาก

Cluster 1 : The Speed & Ease Advocates

    เป็นกลุ่มที่เน้นความคุ้มค่าของเม็ดเงิน มักจะเปรียบเทียบราคาต่อปริมาณ และจะตัดสินใจซื้อแบรนด์ที่ให้โปรโมชั่นที่ดีที่สุดในขณะนั้น



Cluster 2 : The Gentle Perfectionists

    คำอธิบาย: เป็นกลุ่มที่ยอมจ่ายในราคาที่สูงกว่าเพื่อแลกกับความสบายใจและความปลอดภัย สินค้าต้องตอบโจทย์ทั้งเชิงฟังก์ชัน (ปิดหงอก) และเชิงอารมณ์ (ความผ่อนคลาย/กลิ่นหอม)

##**Anomaly Profile & Interpretation**
"""

print("Anomaly Profile & Interpretation\n")
# print("=" * 70)

normal_data  = df[df['Is_Anomaly'] ==  1]
anomaly_data = df[df['Is_Anomaly'] == -1]

print(f"[กลุ่มปกติ — สีเทา] {len(normal_data)} คน ({len(normal_data)/len(df)*100:.1f}%)")
print("   → ลูกค้าที่มีพฤติกรรมเกาะกลุ่มตาม Persona หลัก 3 กลุ่ม\n")

if len(anomaly_data) > 0:
    print(f"[กลุ่มผิดปกติ — สีแดง] {len(anomaly_data)} คน ({len(anomaly_data)/len(df)*100:.1f}%)")
    print("-" * 50)
    print(f"   • อายุที่พบบ่อย  : {anomaly_data['age'].mode()[0]}")
    print(f"   • ปัญหาที่ทำให้แปลก: {anomaly_data['pain_points_std'].mode()[0]}")
    print(f"   • การตีความ: จุดสีแดงคือลูกค้าที่มีคำตอบ 'ขัดแย้ง' ในตัวเอง")
    print(f"     เช่น บอกว่าต้องการความอ่อนโยนแต่เลือกแบรนด์เพราะราคาถูก")
    print(f"     หรือมีความคาดหวังสูงแต่ไม่มีความไม่พอใจใดๆ")
    print(f"     → Isolation Forest จับได้ว่า feature vector ห่างจาก cluster ปกติ")
    print()
    display(anomaly_data[['age', 'region', 'pain_points_std',
                           'brand_reason_std', 'Target_Winning_Zone']])
else:
    print("   ไม่พบกลุ่มที่ผิดปกติอย่างมีนัยสำคัญ")

# print("=" * 70)
print("\nPipeline เสร็จสมบูรณ์ทั้งหมด!")